# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redhooks}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Carlo Miotto"]
  s.date = %q{2011-07-30}
  s.email = %q{support@enbilab.com}
  s.files = [
    "lib/engine.rb",
    "lib/redhooks.rb",
    "lib/redhooks/hook.rb",
    "lib/redhooks/hook/controller_helper.rb",
    "lib/redhooks/hook/listener.rb",
    "lib/redhooks/hook/view_helper.rb",
    "lib/redhooks/hook/view_listener.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Define hooks in your classes. Based on the hook system of Redmine.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

